[package]
name = "orca"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_math = { workspace = true }
geometry = { path = "../geometry" }
bevy_gizmos = { workspace = true }
bevy_render = { workspace = true }
