[package]
name = "coordination"
version = "0.1.0"
edition = "2021"

[dependencies]
geometry = { path = "../geometry" }
orca = { path = "../orca" }

bevy_math = { workspace = true }
bevy_gizmos = { workspace = true }
bevy_render = { workspace = true }

rand = "0.8.5"
approx = "0.3.2"


